eureka:
  instance:
    prefer-ip-address: false
    hostname:
      127.0.0.1

  client:
    register-with-eureka: true
    #下面一定要写 true
    fetch-registry: true
    initial-instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone:
        http://127.0.0.1:8888/eureka/