server:
  port: 8018
spring:
  application:
    name: product-client
  profiles:
    active: dev
  cloud:
    inetutils:
      ignored-interfaces: 'VMware Virtual Ethernet Adapter for VMnet1,VMware Virtual Ethernet Adapter for VMnet8'
    openfeign:
      circuitbreaker:
        enabled: true



ribbon:
  eureka:
    enabled:
      true

