server:
  port: 8010
spring:
  application:
    name: product-service
  cloud:
    inetutils:
      ignored-interfaces: 'VMware Virtual Ethernet Adapter for VMnet1,VMware Virtual Ethernet Adapter for VMnet8'
  datasource:
    url: jdbc:mysql://localhost:3306/tb_product?characterEncoding=utf8&useSSL=false
    username: root
    password: wy2003.5.3
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
